---
apiVersion: v1
kind: Template
metadata:
  name: fabric8-admin-proxy
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: f8adminproxy
    name: f8adminproxy
  spec:
    replicas: 1
    selector:
      app: f8adminproxy
      deploymentconfig: f8adminproxy
    strategy:
      resources:
        limits:
          memory: 1Gi
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: f8adminproxy
          deploymentconfig: f8adminproxy
      spec:
        volumes:
        - name: traefik-config-dir
          secret:
            secretName: f8adminproxy
            items:
              - key: traefik.toml
                path: traefik.toml
        containers:
        - image: ${IMAGE}:${IMAGE_TAG}
          imagePullPolicy: Always
          name: f8adminproxy
          ports:
          - containerPort: 8080
            protocol: TCP
          - containerPort: 8082
            protocol: TCP
          volumeMounts:
            - name: traefik-config-dir
              mountPath: /etc/traefik            
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 8082
              scheme: HTTP
            initialDelaySeconds: 1
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /ping
              port: 8082
              scheme: HTTP
            initialDelaySeconds: 1
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              memory: 1Gi                        
    triggers:
    - type: ConfigChange
- apiVersion: v1
  kind: Service
  metadata:
    name: f8adminproxy
  spec:
    ports:
      - protocol: TCP
        port: 80
        targetPort: 8080
    selector:
      deploymentconfig: f8adminproxy
- kind: Route
  apiVersion: v1
  metadata:
    name: f8adminproxy
  spec:
    host: ''
    to:
      kind: Service
      name: f8adminproxy
parameters:
- name: IMAGE
  value: registry.devshift.net/fabric8-services/fabric8-admin-proxy
- name: IMAGE_TAG
  value: latest
